### PR TITLE
Add SSD support and uuid option support

### PR DESCRIPTION
**Pull request by xiar**

### CODE REVIEW

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by fub2** [comment]
retest this please

**Comment by xiar** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by fub2** [comment]
+1，smoke test failure are all known issues: 1. IPMI console not accessible; 2. QEMU not start because of 9003 is not ready.

**Comment by PaynePei** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* QEMU ******* 
TestName: T33250_idic_KCSSensorList 
ErrorMessage: Failed on local IPMI command ipmitool sensor list, return:  
```

**Comment by PaynePei** [comment]
need @turtle-fly verify this error.

**Comment by xiar** [comment]
retest this please

**Pull request merged**
